name: GCP Authentication

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  WIF_SERVICE_ACCOUNT: infrastructure@hack-team-ai-pandits.iam.gserviceaccount.com
  WIF_PROVIDER: projects/1082330458302/locations/global/workloadIdentityPools/github-2026/providers/github-2026

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v3